apiVersion: v1
kind: Service
metadata:
  name: sso-iam-app-mit-service # Un nome per il tuo Service
spec:
  selector:
    app: sso-iam-app-mit # Seleziona i Pod con questa etichetta
  ports:
    - protocol: TCP
      port: 3000 # La porta su cui il Service sarà esposto esternamente (puoi cambiarla)
      targetPort: 3000 # La porta del container della tua app
  type: LoadBalancer